### ISSUE TITLE
Hiding the "Talking:" bar

### ISSUE THREAD

**Issue by henno** [FuzzyIdeas/ZoomHider#2]
Recently I have noticed that Zoom hides its toolbar itself when I start to screen share and Esc no longer shows the toolbar, only moving the mouse on the small Green/Red "You are screen sharing" bar. Maybe I just fiddled with some settings in the web based settings page on Zoom's website, not sure.

But the reason I found ZoomHider is that I wanted to get rid of the floating "Talking:" bar. Can ZoomHider hide it?

**Comment by alin23** [comment]
Yes, ZoomHider can hide that as well 😊 I just tested it to be sure.

In case you're still seeing the bar, press <kbd>Right Option</kbd> + <kbd>Right Shift</kbd> + <kbd>Z</kbd> two times to toggle hiding again.

![image](https://user-images.githubusercontent.com/3819725/197732793-a9a157dd-9dfb-4c42-ab18-02237d33297b.png)
